### ISSUE TITLE
Plugin fails to load in recent nightly builds

### ISSUE THREAD

**Issue by AlisterH** [sourcepole/qgis-scp-plugin#2]
````
Couldn't load plugin 'scpplugin' due to an error when calling its classFactory() method 

ImportError: cannot import name 'home_plugin_path' from 'qgis.utils' (D:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py) 
Traceback (most recent call last):
  File "D:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\scpplugin\__init__.py", line 27, in classFactory
    from .scpplugin import ScpPlugin
  File "D:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 910, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\scpplugin\scpplugin.py", line 27, in 
    from qgis.utils import home_plugin_path
ImportError: cannot import name 'home_plugin_path' from 'qgis.utils' (D:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py)
````
HOME_PLUGIN_PATH will need to be used in future.
See https://github.com/qgis/QGIS/commit/98c19b38ac93bf9f7d8011facd1ecdbe786788e9

**Comment by HusseinKabbout** [comment]
Thanks for reporting this! I assume this will land in `3.36.0`.
